### ISSUE TITLE
Praise Reel

### ISSUE THREAD

**Issue by calvinckho** [calvinckho/pillar-webapp#15]
Hi @kevin-tolentino, I just found out that the Ionic framework has a page on Animations. You should check it out: https://ionicframework.com/docs/utilities/animations

**Comment by calvinckho** [comment]
@kevin-tolentino, let's use ion-slides as the UI component for the praise reel page. it is located at /app/pages/feature/showpraisereel

to access the demo url, see https://pillar.restvo.com/app/praisereel/60c03fa512ceb93dc8a9b6ec. you can do ionic serve and use https://localhost:xxxx/app/praisereel/60c03fa512ceb93dc8a9b6ec to test the styling.

I have formatted the data for you to use, and I have basically copied and pasted the existing code and styling to get you a quick start.

![Screen Shot 2021-08-08 at 6 01 33 PM](https://user-images.githubusercontent.com/23274587/128651429-2e2eae5b-c2ae-4c25-89f8-fb1d7be9cf95.png)
![Screen Shot 2021-08-08 at 6 01 47 PM](https://user-images.githubusercontent.com/23274587/128651434-848b56e9-fd71-4ac7-8bdf-c1bb45d2c3e2.png)

The few things that you can play around with using ion-slides...

1) the slide autoplay speed
2) I am glad to see that they already have the scrollbar=true option, which shows a nice progress bar at the bottom. see if you can reuse it to resemble Lily's design (i.e. move it to the top, show animation of it moving, etc.)
3) add transition animation, see https://ionicframework.com/docs/api/slides for instructions
4) style it to conform to Lily's design such as the add the close button, add the author info, etc.

Have fun!

**Comment by kevin-tolentino** [comment]
@calvinckho , I have made a PR for this issue. I have noted background image note showing after code snippet implementation. PR can be seen here: https://github.com/calvinckho/pillar-webapp/pull/32

**Comment by calvinckho** [comment]
unfinished tasks:
- [ ] blurred full screen photo background
- [ ] send prayer note/comment
