### ISSUE TITLE
new menu layout

### ISSUE THREAD

**Issue by calvinckho** [calvinckho/pillar-webapp#20]
Hi @lilymuseum, will the Privacy & Security section be inside the setting in your new menu design? Also, we don't have a friends feature yet and would likely only add it in the 2.0 version. Is it okay if we don't include it in the 1.0 version?

![Screen Shot 2021-07-30 at 4 27 03 PM](https://user-images.githubusercontent.com/23274587/127720726-839a9295-3135-4684-b979-64f53f9009b9.png)

**Comment by lilymuseum** [comment]
Hi @calvinckho 
1. Maybe in our 1.0 version, we can place "user profile", "notifications" and "privacy & security" inside the setting like the demo app. I can update it today. 
2. I am ok we don't have the friends feature now. I wonder what we will do when we publish the 1.0 version. Will we test it with a small group such our team, friends, and families?

**Comment by calvinckho** [comment]
Hi @lilymuseum, yes, we will test it within our team, and also with our friends.

**Comment by calvinckho** [comment]
implemented.
