### ISSUE TITLE
permission denied blurred pillar view - alternative design

### ISSUE THREAD

**Issue by calvinckho** [calvinckho/pillar-webapp#24]
@AlexTSung, I am wondering if we can do an alternative design of the pillar permission denied view. Instead of a blurred view, which typically involves using css on the frontend to blur the underlying DOM data, which is not a good practice because in rendering the "blurred" styling of the data on the frontend, we are giving the data way in DOM (a savvy user can use the browser inspector to access the underlying "obfuscated" data). 

I wonder if there is an alternative design which is easier for the dev team to implement without having to build a complicated API rendering mechanism in the backend (which is the right way to do it) to achieve the blurred effect. 

Does @lilymuseum has any other design in mind that can achieve it without us giving the data away?

PS. In essence, the load Moment API should respond to the frontend request with a 401 response: "Permission denied" and nothing else. That is a robust security measure and has been how we are handling all requests.

**Comment by AlexTSung** [comment]
Hey Calvin,

Some ideas for we just did this recently for my work. 

1) We could use a Lorem Ipsem default text under the blur so a savvy user even if they removed the blur wouldn’t get anything valuable.

2) We can redact with white out but in my opinion doesn’t look as a good as blur.

3) We can design a whole new post without blur or white out that is limited in what it shows. Only showing public information and nothing private ie profile photo and name and date posted but nothing else private text or other photos.

My preference is Option 1 or Option 3 (but need to see a design for both before making a decision)

Lily do you have time to try design for those private posts?

Best,
Alex


	 	
Alex Sung, Sr. Product Manager
510.207.7910 | Linkedin
www.alextsung.com

**Comment by calvinckho** [comment]
Hi @AlexTSung, I think Option 3 is best, with a blurred version of a standard layout with some skeleton text/photo and overlaid with the warning text popover. However, IMO even the Pillar title should be private info. I can't really think of anything that is public that a user without permission should be able to see.

**Comment by lilymuseum** [comment]
@AlexTSung @calvinckho I will do option 1 and option 3 this week. My initial thought of the "no access to private post" is a page with illustrations and descriptive text saying, "Oh, this is a private post." And an "explore" button sending them to the homepage or login page.

**Comment by calvinckho** [comment]
implemented.
