### ISSUE TITLE
Add empty state for the Feed page

### ISSUE THREAD

**Issue by calvinckho** [calvinckho/pillar-webapp#7]
![Screen Shot 2021-04-28 at 4 26 39 PM](https://user-images.githubusercontent.com/23274587/116484715-85bb1080-a83e-11eb-868f-24f66a890639.png)

@calixo888, can you add an empty state page to user/feed.page.html when there is no prayer in the array yet? You can use the assets/icon/favicon.png as the graphics for now as we don't have a design yet.

**Comment by calvinckho** [comment]
@kevin-tolentino. The location for empty state assets:

1) My Pillars/My Friends' Pillars: both are located in /src/app/pages/user/feed/feed.page.html, insert before line 64. It is empty when this.datas has no element in its array.
2) Discover: /src/app/pages/user/discover/discover.page.html, insert before line 62. It is empty when this.samples has no element in the array.

**Comment by calvinckho** [comment]
Hi @lilymuseum, I am curious if there is any change to the empty states, for both the pillar feed and the praise feed, before @kevin-tolentino implements them?

**Comment by lilymuseum** [comment]
Hi @calvinckho I think I need to change the graphics and confirm with Alex and Owen. This empty page design is a long time ago. I will do it on weekends.

**Comment by kevin-tolentino** [comment]
@calvinckho , PR for this issue is linked here: https://github.com/calvinckho/pillar-webapp/pull/30

**Comment by calvinckho** [comment]
Thank you!
