### ISSUE TITLE
Implement Answered Prayer status

### ISSUE THREAD

**Issue by calvinckho** [calvinckho/pillar-webapp#8]
https://www.figma.com/file/wDy5edc7lmrYIHSokiTCN4/Pillar-Sign-up?node-id=0%3A1

Store answered status in moment.array_date[moment.array_date.length - 1] field. 

Once a prayer is answered, we can also use chatService.sendReply() to inform participants of the "Mark as Answered" status.

**Comment by calvinckho** [comment]
Hi @kevin-tolentino, I have come up with the data structure to store the answered prayer status. We can discuss some more the next time we meet, but you can also go ahead and try to implement it.

**Comment by kevin-tolentino** [comment]
Alright @calvinckho, I'll take a look, and if I don't get to it today, we can talk about it more tomorrow at our gen meeting

**Comment by calvinckho** [comment]
@kevin-tolentino, since i have added the 'more' ellipsis button with its actionsheet logic in the main branch. so you can work off that branch to add the "mark as answered" logic.

**Comment by kevin-tolentino** [comment]
@calvinckho, thank you for doing that. I will work on it and also talk with you more about it today as needed.
