### ISSUE TITLE
Add the "more" button to Showfeature

### ISSUE THREAD

**Issue by calvinckho** [calvinckho/pillar-webapp#9]
add the "more" button, move the current "share" and "edit" buttons into the "More" action sheet.

![Screen Shot 2021-05-07 at 5 13 30 PM](https://user-images.githubusercontent.com/23274587/117519213-8e56c980-af57-11eb-8ccc-6af5a8eddb65.png)

**Comment by calvinckho** [comment]
also, check with the designers on where to put the "Mark as Answered" button.

**Comment by kevin-tolentino** [comment]
Quick link to design for reference: https://www.figma.com/file/wDy5edc7lmrYIHSokiTCN4/Pillar-Sign-up?node-id=640%3A969

**Comment by calvinckho** [comment]
I have just added the 'more' button to showfeature. It is in the latest webb-production branch.
